name: Build Applications

on:
  push:
    branches:
      - master
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Test
        run: echo "Workflow OK"

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Test
        run: echo "Workflow OK"